from __future__ import annotations

from pathlib import Path

from language_adapters.base import ExecutionCommand
from planner.schemas import ProjectPlan


class Phaser2DAdapter:
    """Example external adapter shape.

    The core PluginManager can discover and import this module. Registering it
    with CodeGenerator/ExecutionEngine is the next extension step for production
    Phaser output.
    """

    language = "JavaScript"
    engine_names = ("Phaser",)

    def supports(self, plan: ProjectPlan) -> bool:
        return plan.engine.lower() == "phaser"

    def generate_project_files(self, plan: ProjectPlan) -> dict[str, str]:
        return {
            "README.md": f"# {plan.project_name}\n\nGenerated by the Phaser plugin adapter example.\n",
            "src/main.js": "console.log('Phaser plugin adapter placeholder');\n",
            "package.json": '{"type":"module","scripts":{"smoke":"node --check src/main.js"}}\n',
        }

    def smoke_commands(self, project_path: Path, install_dependencies: bool = False) -> list[ExecutionCommand]:
        return [ExecutionCommand("Phaser plugin smoke", ["node", "--check", "src/main.js"], project_path)]
