from __future__ import annotations

import json
import textwrap

from planner.schemas import ProjectPlan


def _plan_json(plan: ProjectPlan) -> str:
    return json.dumps(plan.to_dict(), indent=2, ensure_ascii=True)


def common_readme(plan: ProjectPlan) -> str:
    modules = "\n".join(f"- {module}" for module in plan.modules)
    assets = "\n".join(f"- {asset}" for asset in plan.assets)
    commands = "\n".join(f"- `{name}`: `{command}`" for name, command in plan.commands.items())
    return f"""# {plan.project_name}

Generated by OmniGameDev AI.

## Request

{plan.request}

## Plan

- Engine: {plan.engine}
- Language: {plan.language}
- Framework: {plan.framework}
- Game type: {plan.game_type}

## Modules

{modules}

## Assets

{assets}

## Commands

{commands}

## Notes

This project includes placeholder assets, a manifest, and at least one smoke-test path. Replace the generated art and expand the systems as the project grows.
"""


def three_js_template(plan: ProjectPlan) -> dict[str, str]:
    package_json = {
        "name": plan.project_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "dev": "vite --host 127.0.0.1",
            "build": "vite build",
            "smoke": "node --check src/main.js",
        },
        "dependencies": {
            "three": "^0.160.0",
        },
        "devDependencies": {
            "vite": "^5.0.0",
        },
    }
    index_html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__PROJECT_NAME__</title>
    <link rel="stylesheet" href="./src/style.css" />
    <script type="importmap">
      {
        "imports": {
          "three": "https://esm.sh/three@0.160.0"
        }
      }
    </script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="./src/main.js"></script>
  </body>
</html>
""".replace("__PROJECT_NAME__", plan.project_name)

    main_js = r"""import * as THREE from "three";

const PLAN = __PLAN_JSON__;

const dungeonLayout = [
  "############",
  "#P....#....#",
  "#.##..#..B.#",
  "#......E...#",
  "###.####.###",
  "#...#......#",
  "#.E...##...#",
  "#.....#....#",
  "############",
];

const keys = new Set();
const clock = new THREE.Clock();

class Combatant {
  constructor(mesh, health, speed) {
    this.mesh = mesh;
    this.health = health;
    this.maxHealth = health;
    this.speed = speed;
  }
}

function material(color, roughness = 0.78) {
  return new THREE.MeshStandardMaterial({ color, roughness, metalness: 0.04 });
}

function emissiveMaterial(color, intensity = 0.8) {
  return new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: intensity, roughness: 0.45 });
}

function createTorch(scene, x, z) {
  const group = new THREE.Group();
  const post = new THREE.Mesh(new THREE.CylinderGeometry(0.08, 0.12, 1.2, 8), material(0x3b2f2f));
  const flame = new THREE.Mesh(new THREE.SphereGeometry(0.22, 14, 10), emissiveMaterial(0xfacc15, 1.4));
  const light = new THREE.PointLight(0xf59e0b, 2.6, 7, 1.7);
  post.position.y = 0.6;
  flame.position.y = 1.35;
  light.position.y = 1.35;
  group.add(post, flame, light);
  group.position.set(x, 0, z);
  scene.add(group);
  return { group, flame, light, seed: Math.random() * 100 };
}

function createPickup(scene, x, z, index) {
  const gem = new THREE.Mesh(new THREE.OctahedronGeometry(0.34), emissiveMaterial(index % 2 ? 0x5eead4 : 0xfacc15, 0.9));
  gem.position.set(x, 0.7, z);
  gem.castShadow = true;
  scene.add(gem);
  return gem;
}

function createPortal(scene) {
  const ring = new THREE.Mesh(new THREE.TorusGeometry(0.78, 0.08, 12, 32), emissiveMaterial(0x8b5cf6, 1.1));
  ring.position.set(8, 1.0, 6);
  ring.rotation.x = Math.PI / 2;
  scene.add(ring);
  return ring;
}

function tileToWorld(x, z) {
  return new THREE.Vector3((x - 6) * 2, 0, (z - 4) * 2);
}

function buildDungeon(scene) {
  const wallMaterial = material(0x7c6f64);
  const floorMaterial = material(0x2f3a3d);
  const enemyMaterial = material(0xf97316);
  const bossMaterial = material(0xef4444);
  const walls = [];
  const enemies = [];
  const decorativeLights = [];
  const pickups = [];
  let portal = null;
  let playerStart = new THREE.Vector3(0, 0, 0);
  let boss = null;

  const floor = new THREE.Mesh(new THREE.BoxGeometry(26, 0.18, 20), floorMaterial);
  floor.position.y = -0.12;
  floor.receiveShadow = true;
  scene.add(floor);

  decorativeLights.push(createTorch(scene, -8, -6), createTorch(scene, 8, -6), createTorch(scene, -8, 6), createTorch(scene, 8, 6));
  pickups.push(createPickup(scene, -4, -2, 0), createPickup(scene, 2, 4, 1), createPickup(scene, 6, -2, 2));
  portal = createPortal(scene);

  dungeonLayout.forEach((row, z) => {
    [...row].forEach((tile, x) => {
      const position = tileToWorld(x, z);
      if (tile === "#") {
        const wall = new THREE.Mesh(new THREE.BoxGeometry(2, 2.8, 2), wallMaterial);
        wall.position.set(position.x, 1.25, position.z);
        wall.castShadow = true;
        wall.receiveShadow = true;
        scene.add(wall);
        walls.push(wall);
      }
      if (tile === "P") {
        playerStart = position.clone();
      }
      if (tile === "E") {
        const enemy = new THREE.Mesh(new THREE.BoxGeometry(1.1, 1.1, 1.1), enemyMaterial);
        enemy.position.set(position.x, 0.55, position.z);
        enemy.castShadow = true;
        scene.add(enemy);
        enemies.push(new Combatant(enemy, 40, 1.1));
      }
      if (tile === "B") {
        const bossMesh = new THREE.Mesh(new THREE.BoxGeometry(1.8, 1.8, 1.8), bossMaterial);
        bossMesh.position.set(position.x, 0.9, position.z);
        bossMesh.castShadow = true;
        scene.add(bossMesh);
        boss = new Combatant(bossMesh, 180, 0.7);
      }
    });
  });

  return { walls, enemies, boss, playerStart, decorativeLights, pickups, portal };
}

function createHud(root) {
  const hud = document.createElement("div");
  hud.className = "hud";
  hud.innerHTML = `
    <strong>${PLAN.project_name}</strong>
    <span id="status">Explore the dungeon</span>
    <span id="health">HP 100</span>
  `;
  root.appendChild(hud);
  return {
    status: hud.querySelector("#status"),
    health: hud.querySelector("#health"),
  };
}

function updateCamera(camera, player) {
  const target = player.mesh.position;
  camera.position.lerp(new THREE.Vector3(target.x + 6, 7, target.z + 8), 0.08);
  camera.lookAt(target.x, 0.6, target.z);
}

function moveWithCollision(entity, deltaMove, walls) {
  const next = entity.mesh.position.clone().add(deltaMove);
  const blocked = walls.some((wall) => next.distanceTo(wall.position) < 1.35);
  if (!blocked) {
    entity.mesh.position.copy(next);
  }
}

function updateEnemies(player, enemies, boss, walls, delta) {
  const allEnemies = boss ? [...enemies, boss] : enemies;
  allEnemies.forEach((enemy) => {
    if (enemy.health <= 0) {
      enemy.mesh.visible = false;
      return;
    }
    const toPlayer = player.mesh.position.clone().sub(enemy.mesh.position);
    const distance = toPlayer.length();
    if (distance < 8) {
      toPlayer.normalize();
      moveWithCollision(enemy, toPlayer.multiplyScalar(enemy.speed * delta), walls);
    }
    enemy.mesh.rotation.y += delta * 1.8;
    if (distance < 1.25) {
      player.health = Math.max(0, player.health - delta * 12);
    }
  });
}

function updatePlayer(player, walls, delta) {
  const direction = new THREE.Vector3();
  if (keys.has("KeyW") || keys.has("ArrowUp")) direction.z -= 1;
  if (keys.has("KeyS") || keys.has("ArrowDown")) direction.z += 1;
  if (keys.has("KeyA") || keys.has("ArrowLeft")) direction.x -= 1;
  if (keys.has("KeyD") || keys.has("ArrowRight")) direction.x += 1;
  if (direction.length() > 0) {
    direction.normalize().multiplyScalar(player.speed * delta);
    moveWithCollision(player, direction, walls);
  }
  player.mesh.rotation.y += delta * 1.5;
}

function attack(player, enemies, boss, hud) {
  const targets = boss ? [...enemies, boss] : enemies;
  let hit = false;
  targets.forEach((enemy) => {
    if (enemy.health <= 0) return;
    const distance = enemy.mesh.position.distanceTo(player.mesh.position);
    if (distance < 2.4) {
      enemy.health -= 22;
      enemy.mesh.scale.setScalar(Math.max(0.25, enemy.health / enemy.maxHealth));
      hit = true;
    }
  });
  hud.status.textContent = hit ? "Strike landed" : "No enemy in range";
}

function updateDecorations(decorativeLights, pickups, portal, delta) {
  decorativeLights.forEach((torch) => {
    torch.flame.scale.setScalar(0.85 + Math.sin(performance.now() * 0.007 + torch.seed) * 0.12);
    torch.light.intensity = 2.2 + Math.sin(performance.now() * 0.006 + torch.seed) * 0.5;
  });
  pickups.forEach((pickup, index) => {
    if (!pickup.visible) return;
    pickup.rotation.y += delta * (1.8 + index * 0.2);
    pickup.position.y = 0.7 + Math.sin(performance.now() * 0.003 + index) * 0.12;
  });
  if (portal) {
    portal.rotation.z += delta * 1.3;
  }
}

function collectPickups(player, pickups, hud) {
  pickups.forEach((pickup) => {
    if (pickup.visible && pickup.position.distanceTo(player.mesh.position) < 1.2) {
      pickup.visible = false;
      player.health = Math.min(player.maxHealth, player.health + 12);
      hud.status.textContent = "Relic collected";
    }
  });
}

export function createGame(root = document.getElementById("app")) {
  root.innerHTML = "";

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x101416);
  scene.fog = new THREE.Fog(0x101416, 12, 34);

  const camera = new THREE.PerspectiveCamera(60, root.clientWidth / root.clientHeight, 0.1, 100);
  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setSize(root.clientWidth, root.clientHeight);
  renderer.shadowMap.enabled = true;
  root.appendChild(renderer.domElement);

  const ambient = new THREE.HemisphereLight(0xdff7ff, 0x1c1917, 1.2);
  scene.add(ambient);
  const keyLight = new THREE.DirectionalLight(0xfff7cc, 2.5);
  keyLight.position.set(4, 10, 6);
  keyLight.castShadow = true;
  scene.add(keyLight);

  const { walls, enemies, boss, playerStart, decorativeLights, pickups, portal } = buildDungeon(scene);
  const playerMesh = new THREE.Mesh(new THREE.CapsuleGeometry(0.42, 0.7, 6, 12), material(0x5eead4));
  playerMesh.position.set(playerStart.x, 0.75, playerStart.z);
  playerMesh.castShadow = true;
  scene.add(playerMesh);

  const player = new Combatant(playerMesh, 100, 4.2);
  const hud = createHud(root);

  function resize() {
    camera.aspect = root.clientWidth / root.clientHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(root.clientWidth, root.clientHeight);
  }

  function animate() {
    const delta = Math.min(clock.getDelta(), 0.033);
    updatePlayer(player, walls, delta);
    updateEnemies(player, enemies, boss, walls, delta);
    updateDecorations(decorativeLights, pickups, portal, delta);
    collectPickups(player, pickups, hud);
    updateCamera(camera, player);

    hud.health.textContent = `HP ${Math.ceil(player.health)}`;
    if (player.health <= 0) hud.status.textContent = "Defeated - refresh to retry";
    if (boss && boss.health <= 0) hud.status.textContent = "Boss defeated";

    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  }

  window.addEventListener("resize", resize);
  window.addEventListener("keydown", (event) => {
    keys.add(event.code);
    if (event.code === "Space") attack(player, enemies, boss, hud);
  });
  window.addEventListener("keyup", (event) => keys.delete(event.code));

  resize();
  animate();
  return { scene, camera, renderer, plan: PLAN };
}

if (typeof window !== "undefined") {
  window.omniGame = createGame();
}
""".replace("__PLAN_JSON__", _plan_json(plan))

    style_css = """html,
body,
#app {
  height: 100%;
  margin: 0;
}

body {
  background: #101416;
  color: #eef7f7;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  overflow: hidden;
}

canvas {
  display: block;
  width: 100%;
  height: 100%;
}

.hud {
  position: fixed;
  top: 16px;
  left: 16px;
  right: 16px;
  display: flex;
  align-items: center;
  gap: 14px;
  flex-wrap: wrap;
  color: #f8fafc;
  font-size: 14px;
  line-height: 1.2;
  pointer-events: none;
}

.hud span,
.hud strong {
  background: rgba(15, 23, 42, 0.72);
  border: 1px solid rgba(148, 163, 184, 0.28);
  border-radius: 6px;
  padding: 7px 9px;
  backdrop-filter: blur(8px);
}
"""
    return {
        "README.md": common_readme(plan),
        "package.json": json.dumps(package_json, indent=2),
        "index.html": index_html,
        "src/main.js": main_js,
        "src/style.css": style_css,
    }


def pygame_template(plan: ProjectPlan) -> dict[str, str]:
    main_py = r'''from __future__ import annotations

import argparse
import json
import math
import random
from dataclasses import dataclass

PLAN = json.loads(r"""__PLAN_JSON__""")

WIDTH = 960
HEIGHT = 640
TILE = 48

LEVEL = [
    "####################",
    "#P....#............#",
    "#.##..#..E.....B...#",
    "#......E...........#",
    "###.########.#######",
    "#...#..............#",
    "#.E...##.....E.....#",
    "#.....#............#",
    "####################",
]


@dataclass
class Actor:
    rect: object
    health: float
    speed: float
    color: tuple[int, int, int]


def smoke() -> None:
    assert PLAN["project_name"]
    assert "modules" in PLAN
    assert any("player" in module for module in PLAN["modules"])
    print(json.dumps({"ok": True, "engine": "Pygame", "project": PLAN["project_name"]}))


def load_pygame():
    import pygame

    return pygame


def parse_level(pygame):
    walls = []
    enemies = []
    boss = None
    player_start = (TILE * 2, TILE * 2)
    for row_index, row in enumerate(LEVEL):
        for column_index, tile in enumerate(row):
            rect = pygame.Rect(column_index * TILE, row_index * TILE, TILE, TILE)
            if tile == "#":
                walls.append(rect)
            elif tile == "P":
                player_start = rect.center
            elif tile == "E":
                enemies.append(Actor(rect.copy().inflate(-12, -12), 35, 92, (249, 115, 22)))
            elif tile == "B":
                boss = Actor(rect.copy().inflate(12, 12), 160, 54, (239, 68, 68))
    return walls, enemies, boss, player_start


def move_actor(actor, dx, dy, walls):
    actor.rect.x += int(dx)
    for wall in walls:
        if actor.rect.colliderect(wall):
            if dx > 0:
                actor.rect.right = wall.left
            if dx < 0:
                actor.rect.left = wall.right
    actor.rect.y += int(dy)
    for wall in walls:
        if actor.rect.colliderect(wall):
            if dy > 0:
                actor.rect.bottom = wall.top
            if dy < 0:
                actor.rect.top = wall.bottom


def update_enemy(enemy, player, walls, dt):
    if enemy.health <= 0:
        return
    dx = player.rect.centerx - enemy.rect.centerx
    dy = player.rect.centery - enemy.rect.centery
    distance = math.hypot(dx, dy)
    if 1 < distance < 360:
        move_actor(enemy, dx / distance * enemy.speed * dt, dy / distance * enemy.speed * dt, walls)
    if enemy.rect.colliderect(player.rect):
        player.health = max(0, player.health - 16 * dt)


def draw_world(pygame, screen, font, walls, enemies, boss, player, status):
    screen.fill((15, 20, 22))
    for row_index, row in enumerate(LEVEL):
        for column_index, _ in enumerate(row):
            rect = pygame.Rect(column_index * TILE, row_index * TILE, TILE, TILE)
            pygame.draw.rect(screen, (47, 58, 61), rect, 1)
    for wall in walls:
        pygame.draw.rect(screen, (124, 111, 100), wall)
    for enemy in enemies:
        if enemy.health > 0:
            pygame.draw.rect(screen, enemy.color, enemy.rect, border_radius=6)
    if boss and boss.health > 0:
        pygame.draw.rect(screen, boss.color, boss.rect, border_radius=10)
    pygame.draw.rect(screen, player.color, player.rect, border_radius=8)
    hud = font.render(f"{PLAN['project_name']}   HP {math.ceil(player.health)}   {status}", True, (238, 247, 247))
    screen.blit(hud, (18, 16))


def run_game():
    pygame = load_pygame()
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption(PLAN["project_name"])
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("consolas", 18)
    walls, enemies, boss, player_start = parse_level(pygame)
    player = Actor(pygame.Rect(0, 0, 30, 30), 100, 180, (94, 234, 212))
    player.rect.center = player_start
    status = "WASD move, SPACE attack, ESC quit"

    running = True
    while running:
        dt = clock.tick(60) / 1000
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
                hit = False
                for enemy in enemies + ([boss] if boss else []):
                    if enemy and enemy.health > 0 and player.rect.inflate(64, 64).colliderect(enemy.rect):
                        enemy.health -= 24
                        hit = True
                status = "Strike landed" if hit else "No enemy in range"

        keys = pygame.key.get_pressed()
        dx = (keys[pygame.K_d] - keys[pygame.K_a]) * player.speed * dt
        dy = (keys[pygame.K_s] - keys[pygame.K_w]) * player.speed * dt
        move_actor(player, dx, dy, walls)

        for enemy in enemies:
            update_enemy(enemy, player, walls, dt)
        if boss:
            update_enemy(boss, player, walls, dt)
            if boss.health <= 0:
                status = "Boss defeated"
        if player.health <= 0:
            status = "Defeated"

        draw_world(pygame, screen, font, walls, enemies, boss, player, status)
        pygame.display.flip()

    pygame.quit()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--smoke", action="store_true", help="Run deterministic smoke checks.")
    args = parser.parse_args()
    if args.smoke:
        smoke()
    else:
        run_game()


if __name__ == "__main__":
    main()
'''.replace("__PLAN_JSON__", _plan_json(plan))
    return {
        "README.md": common_readme(plan),
        "requirements.txt": "pygame>=2.5\n",
        "main.py": main_py,
    }


def cpp_template(plan: ProjectPlan) -> dict[str, str]:
    main_cpp = r'''#include <chrono>
#include <cmath>
#include <iostream>
#include <string>
#include <thread>
#include <vector>

struct Actor {
    std::string name;
    float x;
    float y;
    float health;
    float speed;
};

static const char* PROJECT_NAME = "__PROJECT_NAME__";

void smoke() {
    std::cout << "{\"ok\":true,\"engine\":\"Basic C++ Engine\",\"project\":\"" << PROJECT_NAME << "\"}" << std::endl;
}

void simulate() {
    Actor player{"player", 1.0f, 1.0f, 100.0f, 1.6f};
    std::vector<Actor> enemies = {
        {"enemy-a", 7.0f, 2.0f, 35.0f, 0.9f},
        {"enemy-b", 4.0f, 5.0f, 35.0f, 0.9f},
        {"boss", 9.0f, 4.0f, 180.0f, 0.5f},
    };

    std::cout << PROJECT_NAME << " simulation starting" << std::endl;
    for (int frame = 0; frame < 12; ++frame) {
        player.x += 0.35f;
        for (auto& enemy : enemies) {
            float dx = player.x - enemy.x;
            float dy = player.y - enemy.y;
            float distance = std::sqrt(dx * dx + dy * dy);
            if (distance > 0.01f) {
                enemy.x += dx / distance * enemy.speed * 0.1f;
                enemy.y += dy / distance * enemy.speed * 0.1f;
            }
            if (distance < 1.4f) {
                player.health -= 2.0f;
            }
        }
        std::cout << "frame=" << frame << " player=(" << player.x << "," << player.y << ") hp=" << player.health << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }
}

int main(int argc, char** argv) {
    if (argc > 1 && std::string(argv[1]) == "--smoke") {
        smoke();
        return 0;
    }
    simulate();
    return 0;
}
'''.replace("__PROJECT_NAME__", plan.project_name)
    cmake = f"""cmake_minimum_required(VERSION 3.16)
project({plan.project_name.replace("-", "_")})
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(omnigame main.cpp)
"""
    smoke_py = """from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
compiler = shutil.which("g++") or shutil.which("clang++")
if compiler is None:
    print("No C++ compiler found; source files are present for engine import.")
    raise SystemExit(0)

binary = root / "omnigame-smoke.exe"
subprocess.run([compiler, "main.cpp", "-std=c++17", "-O2", "-o", str(binary)], cwd=root, check=True)
subprocess.run([str(binary), "--smoke"], cwd=root, check=True)
"""
    return {
        "README.md": common_readme(plan),
        "main.cpp": main_cpp,
        "CMakeLists.txt": cmake,
        "tools/smoke.py": smoke_py,
    }


def unity_template(plan: ProjectPlan) -> dict[str, str]:
    game_manager = r'''using UnityEngine;

public class OmniGameManager : MonoBehaviour
{
    public string projectName = "__PROJECT_NAME__";
    public PlayerController player;
    public EnemyAI[] enemies;

    private void Start()
    {
        Debug.Log($"{projectName} initialized with {enemies.Length} enemies.");
    }

    private void Update()
    {
        if (player != null && player.Health <= 0)
        {
            Debug.Log("Player defeated. Reload the scene to retry.");
        }
    }
}
'''.replace("__PROJECT_NAME__", plan.project_name)
    player = r'''using UnityEngine;

[RequireComponent(typeof(CharacterController))]
public class PlayerController : MonoBehaviour
{
    public float moveSpeed = 5f;
    public float attackRange = 2f;
    public float attackDamage = 25f;
    public float Health { get; private set; } = 100f;

    private CharacterController controller;

    private void Awake()
    {
        controller = GetComponent<CharacterController>();
    }

    private void Update()
    {
        float horizontal = Input.GetAxis("Horizontal");
        float vertical = Input.GetAxis("Vertical");
        Vector3 movement = new Vector3(horizontal, 0f, vertical);
        controller.SimpleMove(movement * moveSpeed);

        if (Input.GetKeyDown(KeyCode.Space))
        {
            Attack();
        }
    }

    public void Damage(float amount)
    {
        Health = Mathf.Max(0f, Health - amount);
    }

    private void Attack()
    {
        Collider[] hits = Physics.OverlapSphere(transform.position, attackRange);
        foreach (Collider hit in hits)
        {
            EnemyAI enemy = hit.GetComponent<EnemyAI>();
            if (enemy != null)
            {
                enemy.Damage(attackDamage);
            }
        }
    }
}
'''
    enemy = r'''using UnityEngine;

public class EnemyAI : MonoBehaviour
{
    public float health = 50f;
    public float moveSpeed = 2f;
    public float attackDamage = 8f;
    public float detectionRange = 10f;
    public bool isBoss;

    private Transform player;

    private void Start()
    {
        PlayerController controller = FindObjectOfType<PlayerController>();
        if (controller != null)
        {
            player = controller.transform;
        }
        if (isBoss)
        {
            health *= 4f;
            transform.localScale *= 1.8f;
        }
    }

    private void Update()
    {
        if (player == null || health <= 0f)
        {
            return;
        }

        float distance = Vector3.Distance(transform.position, player.position);
        if (distance < detectionRange)
        {
            Vector3 direction = (player.position - transform.position).normalized;
            transform.position += direction * moveSpeed * Time.deltaTime;
            transform.LookAt(player.position);
        }
    }

    public void Damage(float amount)
    {
        health -= amount;
        if (health <= 0f)
        {
            gameObject.SetActive(false);
        }
    }
}
'''
    scene_notes = """# Unity Scene Setup

1. Create a new Unity 3D project.
2. Copy the `Assets` folder from this generated project into the Unity project.
3. Add a floor, walls, a capsule player with `CharacterController` and `PlayerController`, and cube enemies with `EnemyAI`.
4. Add `OmniGameManager` to an empty scene object and assign the player and enemies.
5. Press Play.
"""
    return {
        "README.md": common_readme(plan),
        "Assets/Scripts/OmniGameManager.cs": game_manager,
        "Assets/Scripts/PlayerController.cs": player,
        "Assets/Scripts/EnemyAI.cs": enemy,
        "Assets/OmniGameDev/SceneSetup.md": scene_notes,
    }
